"""Test DataIngestor by loading the synthetic_output.csv file.

This script demonstrates loading the CSV generated by run_synthetic_ingest.py
and shows the shape of numeric features that were extracted.
"""
from data_ingest import DataIngestor
import os

def main():
    # Get path to synthetic_output.csv in same directory as this script
    here = os.path.dirname(__file__)
    csv_path = os.path.join(here, 'synthetic_output.csv')
    
    print(f'Loading CSV from: {csv_path}')
    
    # Create DataIngestor and load the CSV
    di = DataIngestor()
    
    # First load all numeric columns (default behavior)
    X = di.ingest('csv', source=csv_path)
    print('\nAll numeric features:')
    print(f'Shape: {X.shape}')  # Should be (200, 3) - id, sensor_value, temperature
    print(f'First 5 rows:\n{X[:5]}')
    
    # Then demonstrate loading specific columns
    feature_cols = ['sensor_value', 'temperature']
    X_selected = di.ingest('csv', source=csv_path, feature_columns=feature_cols)
    print(f'\nSelected features ({feature_cols}):')
    print(f'Shape: {X_selected.shape}')  # Should be (200, 2)
    print(f'First 5 rows:\n{X_selected[:5]}')

if __name__ == '__main__':
    main()